name: sheveegan
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.5+7

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  bloc: ^8.1.4
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.15.5
  cupertino_icons: ^1.0.8
  dartz:
  device_preview: ^1.1.0
  equatable:
  firebase_app_check: ^0.2.2+4
  firebase_auth: ^4.19.4
  firebase_core: ^2.25.4
  firebase_storage: ^11.7.4
  fl_chart: ^0.67.0
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  flutter_bloc: ^8.1.5
  flutter_dotenv: ^5.1.0
  flutter_facebook_auth: ^6.2.0
  flutter_launcher_icons: ^0.13.1
  #  flutter_localizations:
  flutter_native_splash: ^2.4.0
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.9.0
  font_awesome_flutter: ^10.7.0
  geolocator: ^11.0.0
  get_it: ^7.7.0
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.6.1
  google_mlkit_text_recognition: ^0.13.0
  google_sign_in: ^6.2.1
  http: ^1.2.1
  iconly: ^1.0.1
  image_picker: ^1.1.1
  intl: ^0.18.1
  provider: ^6.1.1
  simple_animations: ^5.0.2
  url_launcher: ^6.2.6
  uuid: ^4.4.0
  webview_flutter: ^4.7.0
  #  lint:
  #  googleapis: ^9.1.0


  #  animated_splash_screen:


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.


dev_dependencies:
  bloc_test: ^9.1.7
  fake_cloud_firestore: ^2.5.1
  firebase_auth_mocks: ^0.13.0
  firebase_storage_mocks: ^0.6.1
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter
  google_sign_in_mocks: ^0.3.0
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0



flutter_launcher_icons:
  android: true
  ios: true
  image_path_android: "assets/logo/VeganBestieLogo.png"
  image_path_ios: "assets/logo/VeganBestieLogo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
#  web:
#    generate: true
#    image_path: "path/to/image.png"
#    background_color: "#hexcode"
#    theme_color: "#hexcode"
#  windows:
#    generate: true
#    image_path: "path/to/image.png"
#    icon_size: 48 # min:48, max:256, default: 48
#  macos:
#    generate: true
#    image_path: "path/to/image.png"


flutter_native_splash:
  android: true
  ios: true
  color: "#43A047"
  #  color: "#FFFFFF"
  #background_image: "assets/background.png"
  image: assets/logo/VeganBestieLogo.png
  #  image: assets/logo/VeganBestie_BlackLogp.png
  #  image: assets/logo/VeganBestie_nobackground_fixed.png
  #  image: assets/logo/Logo-3.png
  #color_dark: "#042a49"
  #background_image_dark: "assets/dark-background.png"
  #image_dark: assets/splash-invert.png
  #android_gravity: center
  #fullscreen: true
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/
    - assets/icon/
    - assets/logo/
    - .env
    - test/fixtures/food_product.json
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: VeganIcon
      fonts:
        - asset: assets/icon/VeganIcon.ttf
    - family: BarcodeIcon
      fonts:
        - asset: assets/icon/Barcode.ttf
  #         - asset: fonts/TrajanPro_Bold.ttf
  #           weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
