# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build and Release

#1
on:
  #2
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  #3
  workflow_dispatch:

#4
jobs:
  #5
  build:
    #6
    runs-on: ubuntu-latest

    #7
    steps:
      #8
      - name: Checkout Repository
        uses: actions/checkout@v4
      #9 Set Up Java
      - name: Set Up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21.x'
          cache: 'gradle'
      #10
      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          #11
          channel: 'stable'
          #          flutter-version-file: 'pubspec.yaml'
          flutter-version: "3.19.5"
          cache: true
      #12
      - run: flutter clean

      - name: Install Dependencies
        run: flutter pub get

      #13
      #      - name: Test flutter app
      #        run: flutter test
      #14
      - name: Build APK
        run: flutter build apk
      #        run: flutter build apk --release --verbose
      #15
      - name: Build appBundle
        run: flutter build appbundle

      #16
      - name: Build IPA
        run:
          flutter build ipa --no-codesign
      - name: Compress Archives and IPAs
        run: |
          cd build
          tar -czf ios_build.tar.gz ios
      #17
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Releases
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/bundle/release/app-release.aab
            build/ios_build.tar.gz

      #18

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/app-release.apk,build/app/outputs/bundle/release/app-release.aab,build/ios_build.tar.gz"
          tag: v1.1.${{ github.run_number }}
#          token: ${{ secrets.TOKEN }}

#      - name: Push to Releases
#        uses: ncipollo/release-action@v1
#        with:
#          artifacts: "build/app/outputs/bundle/release/*"
#          tag: v1.0.${{github.run_number}}
