# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build and Release

#1
on:
  #2
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  #3
  workflow_dispatch:

#4
jobs:
  #5
  build:
    #6
    runs-on: ubuntu-latest

    #7
    steps:
      #8
      - uses: actions/checkout@v3
      #9
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '12.x'
          cache: 'gradle'
      #10
      - uses: subosito/flutter-action@v2
        with:
          #11
          flutter-version: "3.19.5"
          channel: 'stable'
          cache: true
      #12
      - name: Get dependencies
        run: flutter pub get
      #      - run: flutter clean
      # Runs a set of commands using the runners shell
      - name: Start release build
        run: flutter build appbundle
#      - name: Push to Releases
#        uses: ncipollo/release-action@v1
#        with:
#          artifacts: "build/app/outputs/bundle/release/*"
#          tag: v1.0.${{github.run_number}}
